import gradio as gr
import sys
import os

# Import feature extractor
import importlib.util
spec = importlib.util.spec_from_file_location("inference", "07_inference.py")
inference = importlib.util.module_from_spec(spec)
spec.loader.exec_module(inference)
DetectAIEnsemble = inference.DetectAIEnsemble

# Initialize ensemble
print("Loading DetectAI models...")
ensemble = DetectAIEnsemble()
print("✓ Models loaded successfully!\n")

def classify_text(text):
    """Classify text and return results"""
    
    if not text or len(text.strip()) < 10:
        return "⚠ Please enter at least 10 characters.", None, None, None
    
    result = ensemble.predict(text)
    
    # Format results
    label_text = f"## {result['label']}"
    
    if result['label'] == 'AI-Generated':
        label_text += " 🤖"
    else:
        label_text += " 👤"
    
    confidence = f"{result['confidence']:.1%}"
    
    # Create probability distribution
    probs = {
        'Human-Written': result['human_probability'],
        'AI-Generated': result['ai_probability']
    }
    
    # Individual model predictions
    individual = "### Individual Model Predictions:\n\n"
    for model_name, prob in result['individual_predictions'].items():
        individual += f"- **{model_name}**: {prob:.2%} (AI probability)\n"
    
    return label_text, confidence, probs, individual

# Create Gradio interface (Gradio 6.0 style)
with gr.Blocks(title="DetectAI - Human vs AI Text Classifier") as demo:
    
    gr.Markdown("# 🔍 DetectAI: Human vs AI-Generated Text Classifier")
    gr.Markdown("Enter text below to classify whether it was written by a human or generated by AI.")
    gr.Markdown("*Uses ensemble of TF-IDF, Random Forest, and Transformer models with explainable AI.*")
    
    with gr.Row():
        with gr.Column():
            text_input = gr.Textbox(
                label="Input Text",
                placeholder="Paste or type your text here...",
                lines=10
            )
            classify_btn = gr.Button("🔍 Classify Text", variant="primary", size="lg")
        
        with gr.Column():
            label_output = gr.Markdown(label="Prediction")
            confidence_output = gr.Textbox(label="Confidence Score", interactive=False)
            prob_plot = gr.Label(label="Probability Distribution", num_top_classes=2)
            individual_output = gr.Markdown(label="Model Breakdown")
    
    classify_btn.click(
        fn=classify_text,
        inputs=text_input,
        outputs=[label_output, confidence_output, prob_plot, individual_output]
    )
    
    # Examples
    gr.Examples(
        examples=[
            ["I really enjoyed the movie last night! The plot was engaging and the acting was superb. Can't wait to see what they do next."],
            ["The implementation of the aforementioned methodology demonstrates significant improvements in performance metrics across multiple domains."],
            ["Hey! What's up? I'm so excited about the weekend plans. Can't wait to see you! Let me know if you're free."],
            ["In conclusion, the systematic analysis presented herein provides comprehensive insights into the subject matter under consideration."],
            ["My dog does the funniest thing when I come home - he runs in circles for like 5 minutes straight lol. It's adorable but also kinda weird."]
        ],
        inputs=text_input,
        label="Example Texts (Click to load)"
    )
    
    gr.Markdown("---")
    gr.Markdown("### About DetectAI")
    gr.Markdown("""
    This system uses multiple AI detection techniques:
    - **Stylometric Analysis**: Examines writing style patterns (30+ features)
    - **Linguistic Features**: Analyzes readability, POS tags, and discourse markers
    - **Machine Learning**: TF-IDF + Logistic Regression and Random Forest
    - **Deep Learning**: Transformer models (RoBERTa/DistilBERT)
    - **Explainable AI**: LIME and SHAP for interpretability
    
    **Key Detection Signals:**
    - Function word usage patterns
    - Sentence complexity and structure
    - Lexical diversity metrics
    - Readability scores
    - Named entity distributions
    """)

if __name__ == "__main__":
    print("="*80)
    print("Launching DetectAI Web Interface...")
    print("="*80 + "\n")
    
    # Launch with Gradio 6.0 syntax
    demo.launch(
        share=False,  # Set to True if you want public link (requires internet)
        server_name="127.0.0.1",  # Use localhost instead of 0.0.0.0
        server_port=7860,
        theme=gr.themes.Soft()
    )
